# Generated by Django 3.1 on 2020-09-06 15:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('company_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Nombre del Evento')),
                ('project_description', models.CharField(max_length=250, verbose_name='Descripción del Proyecto  ')),
                ('project_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor a Pagar')),
                ('project_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.company', verbose_name='Empresa del Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_creation_date', models.DateTimeField(auto_now_add=True)),
                ('designer_first_name', models.CharField(max_length=50, verbose_name='Nombre Diseñador')),
                ('designer_last_name', models.CharField(max_length=50, verbose_name='Apellido Diseñador')),
                ('designer_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('design_file', models.FileField(upload_to='designs_library/processing/default.jpg')),
                ('design_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Solicitado')),
                ('design_status', models.CharField(default='En Proceso', max_length=15)),
                ('design_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.project')),
            ],
        ),
    ]
