# Generated by Django 3.1 on 2020-09-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
