# Generated by Django 3.1 on 2020-09-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
    ]
