# Generated by Django 3.1 on 2020-09-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_delete_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_creation_date', models.DateTimeField(auto_now_add=True)),
                ('designer_first_name', models.CharField(max_length=50, verbose_name='Nombre Diseñador')),
                ('designer_last_name', models.CharField(max_length=50, verbose_name='Apellido Diseñador')),
                ('designer_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('design_file', models.FileField(upload_to='designs_library/processing/default.jpg')),
                ('design_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Solicitado')),
                ('design_status', models.CharField(default='En Proceso', max_length=15)),
                ('design_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.project')),
            ],
        ),
    ]
